import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const exercises = [
    // ─── CHEST ───────────────────────────────────────────────────────────────
    {
        name: 'Barbell Bench Press',
        category: 'Chest',
        primaryMuscle: 'Pectoralis Major',
        secondaryMuscles: ['Anterior Deltoid', 'Triceps'],
        bodyPartFocus: 'Chest',
        equipment: 'barbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
        sourceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/BBBenchPress',
        instructions: 'Lie on bench, grip bar slightly wider than shoulder width. Lower bar to mid-chest, press up.',
        safetyNotes: 'Use a spotter. Do not bounce bar off chest. Keep feet flat on floor.',
        isSystem: true,
    },
    {
        name: 'Incline Dumbbell Press',
        category: 'Chest',
        primaryMuscle: 'Pectoralis Major (Upper)',
        secondaryMuscles: ['Anterior Deltoid', 'Triceps'],
        bodyPartFocus: 'Chest',
        equipment: 'dumbbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
        sourceUrl: 'https://exrx.net/WeightExercises/PectoralClavicular/DBInclineBenchPress',
        instructions: 'Set bench to 30-45°. Press dumbbells up and together at the top.',
        safetyNotes: 'Do not arch lower back excessively. Control the descent.',
        isSystem: true,
    },
    {
        name: 'Push-Up',
        category: 'Chest',
        primaryMuscle: 'Pectoralis Major',
        secondaryMuscles: ['Anterior Deltoid', 'Triceps', 'Core'],
        bodyPartFocus: 'Chest',
        equipment: 'bodyweight',
        trackingType: 'reps_only',
        demoVideoUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
        sourceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/BWPushup',
        instructions: 'Plank position, hands shoulder-width apart. Lower chest to floor, press back up.',
        safetyNotes: 'Keep core engaged. Do not let hips sag.',
        isSystem: true,
    },
    {
        name: 'Dumbbell Chest Fly',
        category: 'Chest',
        primaryMuscle: 'Pectoralis Major',
        secondaryMuscles: ['Anterior Deltoid'],
        bodyPartFocus: 'Chest',
        equipment: 'dumbbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=eozdVDA78K0',
        sourceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/DBFly',
        instructions: 'Lie flat, arms wide with slight elbow bend. Arc dumbbells together over chest.',
        safetyNotes: 'Use light weight. Avoid locking elbows. Control the stretch.',
        isSystem: true,
    },
    {
        name: 'Cable Crossover',
        category: 'Chest',
        primaryMuscle: 'Pectoralis Major',
        secondaryMuscles: ['Anterior Deltoid'],
        bodyPartFocus: 'Chest',
        equipment: 'cable',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=taI4XduLpTk',
        sourceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/CBCrossover',
        instructions: 'Stand between high pulleys. Pull cables down and together in front of chest.',
        safetyNotes: 'Lean slightly forward. Maintain slight bend in elbows throughout.',
        isSystem: true,
    },

    // ─── BACK ────────────────────────────────────────────────────────────────
    {
        name: 'Lat Pulldown',
        category: 'Back',
        primaryMuscle: 'Latissimus Dorsi',
        secondaryMuscles: ['Biceps', 'Rear Deltoid', 'Rhomboids'],
        bodyPartFocus: 'Back',
        equipment: 'cable',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
        sourceUrl: 'https://exrx.net/WeightExercises/LatissimusDorsi/CBFrontPulldown',
        instructions: 'Grip bar wide, sit with thighs under pads. Pull bar to upper chest, squeezing lats.',
        safetyNotes: 'Do not pull behind neck. Keep torso upright with slight lean back.',
        isSystem: true,
    },
    {
        name: 'Seated Cable Row',
        category: 'Back',
        primaryMuscle: 'Rhomboids',
        secondaryMuscles: ['Latissimus Dorsi', 'Biceps', 'Rear Deltoid'],
        bodyPartFocus: 'Back',
        equipment: 'cable',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=GZbfZ033f74',
        sourceUrl: 'https://exrx.net/WeightExercises/BackGeneral/CBSeatedRow',
        instructions: 'Sit upright, feet on platform. Pull handle to abdomen, squeeze shoulder blades.',
        safetyNotes: 'Do not round lower back. Avoid using momentum.',
        isSystem: true,
    },
    {
        name: 'Pull-Up',
        category: 'Back',
        primaryMuscle: 'Latissimus Dorsi',
        secondaryMuscles: ['Biceps', 'Rear Deltoid', 'Core'],
        bodyPartFocus: 'Back',
        equipment: 'bodyweight',
        trackingType: 'reps_only',
        demoVideoUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
        sourceUrl: 'https://exrx.net/WeightExercises/LatissimusDorsi/BWPullup',
        instructions: 'Hang from bar, overhand grip. Pull body up until chin clears bar, lower slowly.',
        safetyNotes: 'Avoid kipping/swinging for strength work. Full range of motion.',
        isSystem: true,
    },
    {
        name: 'Dumbbell Row',
        category: 'Back',
        primaryMuscle: 'Latissimus Dorsi',
        secondaryMuscles: ['Rhomboids', 'Biceps', 'Rear Deltoid'],
        bodyPartFocus: 'Back',
        equipment: 'dumbbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=roCP6wCXPqo',
        sourceUrl: 'https://exrx.net/WeightExercises/LatissimusDorsi/DBBentOverRow',
        instructions: 'Brace one knee/hand on bench. Pull dumbbell to hip, keeping elbow close to body.',
        safetyNotes: 'Keep back flat. Do not rotate torso excessively.',
        isSystem: true,
    },
    {
        name: 'Deadlift',
        category: 'Back',
        primaryMuscle: 'Erector Spinae',
        secondaryMuscles: ['Glutes', 'Hamstrings', 'Trapezius', 'Latissimus Dorsi'],
        bodyPartFocus: 'Back',
        equipment: 'barbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
        sourceUrl: 'https://exrx.net/WeightExercises/GluteMaximus/BBDeadlift',
        instructions: 'Bar over mid-foot, hip-width stance. Hip hinge, keep back neutral, drive hips forward.',
        safetyNotes: 'Never round lower back under load. Warm up thoroughly. Use belt for heavy sets.',
        isSystem: true,
    },

    // ─── SHOULDERS ───────────────────────────────────────────────────────────
    {
        name: 'Overhead Press',
        category: 'Shoulders',
        primaryMuscle: 'Anterior Deltoid',
        secondaryMuscles: ['Lateral Deltoid', 'Triceps', 'Upper Trapezius'],
        bodyPartFocus: 'Shoulders',
        equipment: 'barbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
        sourceUrl: 'https://exrx.net/WeightExercises/DeltoidAnterior/BBMilitaryPress',
        instructions: 'Stand, bar at shoulder height. Press overhead until arms locked, lower to clavicle.',
        safetyNotes: 'Do not lean back excessively. Keep core braced.',
        isSystem: true,
    },
    {
        name: 'Dumbbell Lateral Raise',
        category: 'Shoulders',
        primaryMuscle: 'Lateral Deltoid',
        secondaryMuscles: ['Anterior Deltoid', 'Supraspinatus'],
        bodyPartFocus: 'Shoulders',
        equipment: 'dumbbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
        sourceUrl: 'https://exrx.net/WeightExercises/DeltoidLateral/DBLateralRaise',
        instructions: 'Stand with dumbbells at sides. Raise arms to shoulder height, slight bend in elbows.',
        safetyNotes: 'Use controlled movement. Avoid shrugging. Do not swing.',
        isSystem: true,
    },
    {
        name: 'Front Raise',
        category: 'Shoulders',
        primaryMuscle: 'Anterior Deltoid',
        secondaryMuscles: ['Lateral Deltoid', 'Upper Pectoralis'],
        bodyPartFocus: 'Shoulders',
        equipment: 'dumbbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=gkZzkGMtzA4',
        sourceUrl: 'https://exrx.net/WeightExercises/DeltoidAnterior/DBFrontRaise',
        instructions: 'Stand with dumbbells in front of thighs. Raise one or both arms to shoulder height.',
        safetyNotes: 'Keep slight bend in elbows. Do not swing body.',
        isSystem: true,
    },
    {
        name: 'Rear Delt Fly',
        category: 'Shoulders',
        primaryMuscle: 'Posterior Deltoid',
        secondaryMuscles: ['Rhomboids', 'Infraspinatus', 'Teres Minor'],
        bodyPartFocus: 'Shoulders',
        equipment: 'dumbbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=EA7u4Q_8HQ0',
        sourceUrl: 'https://exrx.net/WeightExercises/DeltoidPosterior/DBBentLateralRaise',
        instructions: 'Bend forward at hips, dumbbells hanging. Raise arms out to sides, squeezing rear delts.',
        safetyNotes: 'Use light weight. Keep back flat.',
        isSystem: true,
    },

    // ─── BICEPS ──────────────────────────────────────────────────────────────
    {
        name: 'Barbell Bicep Curl',
        category: 'Biceps',
        primaryMuscle: 'Biceps Brachii',
        secondaryMuscles: ['Brachialis', 'Brachioradialis'],
        bodyPartFocus: 'Arms',
        equipment: 'barbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=kwG2ipFRgfo',
        sourceUrl: 'https://exrx.net/WeightExercises/Biceps/BBCurl',
        instructions: 'Stand with underhand grip on bar. Curl bar to shoulder height, lower slowly.',
        safetyNotes: 'Do not swing back. Keep elbows fixed at sides.',
        isSystem: true,
    },
    {
        name: 'Dumbbell Hammer Curl',
        category: 'Biceps',
        primaryMuscle: 'Brachialis',
        secondaryMuscles: ['Biceps Brachii', 'Brachioradialis'],
        bodyPartFocus: 'Arms',
        equipment: 'dumbbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=zC3nLlEvin4',
        sourceUrl: 'https://exrx.net/WeightExercises/Brachialis/DBHammerCurl',
        instructions: 'Neutral grip (palms facing in). Curl dumbbells to shoulder height.',
        safetyNotes: 'Keep wrists neutral throughout. Avoid swinging.',
        isSystem: true,
    },

    // ─── TRICEPS ─────────────────────────────────────────────────────────────
    {
        name: 'Triceps Pushdown',
        category: 'Triceps',
        primaryMuscle: 'Triceps Brachii',
        secondaryMuscles: [],
        bodyPartFocus: 'Arms',
        equipment: 'cable',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=2-LAMcpzODU',
        sourceUrl: 'https://exrx.net/WeightExercises/Triceps/CBPushdown',
        instructions: 'Stand at cable machine, elbows at sides. Push bar or rope down until arms extended.',
        safetyNotes: 'Keep elbows fixed. Do not lean forward excessively.',
        isSystem: true,
    },
    {
        name: 'Overhead Triceps Extension',
        category: 'Triceps',
        primaryMuscle: 'Triceps Brachii (Long Head)',
        secondaryMuscles: [],
        bodyPartFocus: 'Arms',
        equipment: 'dumbbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=YbX7Wd8jQ-Q',
        sourceUrl: 'https://exrx.net/WeightExercises/Triceps/DBTricepsExtension',
        instructions: 'Hold dumbbell overhead with both hands. Lower behind head, extend up.',
        safetyNotes: 'Keep elbows close to head. Control the descent to protect elbow joints.',
        isSystem: true,
    },
    {
        name: 'Close-Grip Bench Press',
        category: 'Triceps',
        primaryMuscle: 'Triceps Brachii',
        secondaryMuscles: ['Pectoralis Major', 'Anterior Deltoid'],
        bodyPartFocus: 'Arms',
        equipment: 'barbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=nEF0bv2FW94',
        sourceUrl: 'https://exrx.net/WeightExercises/Triceps/BBCloseGripBenchPress',
        instructions: 'Grip bar shoulder-width or closer. Lower bar to lower chest, press up.',
        safetyNotes: 'Do not grip too narrow. Keep elbows close to body.',
        isSystem: true,
    },

    // ─── LEGS ────────────────────────────────────────────────────────────────
    {
        name: 'Barbell Squat',
        category: 'Legs',
        primaryMuscle: 'Quadriceps',
        secondaryMuscles: ['Glutes', 'Hamstrings', 'Erector Spinae', 'Core'],
        bodyPartFocus: 'Legs',
        equipment: 'barbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
        sourceUrl: 'https://exrx.net/WeightExercises/Quadriceps/BBSquat',
        instructions: 'Bar on upper traps, feet shoulder-width. Squat until thighs parallel, drive up.',
        safetyNotes: 'Keep chest up, knees tracking over toes. Do not round lower back.',
        isSystem: true,
    },
    {
        name: 'Leg Press',
        category: 'Legs',
        primaryMuscle: 'Quadriceps',
        secondaryMuscles: ['Glutes', 'Hamstrings'],
        bodyPartFocus: 'Legs',
        equipment: 'machine',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
        sourceUrl: 'https://exrx.net/WeightExercises/Quadriceps/LVLegPress',
        instructions: 'Sit in machine, feet shoulder-width on platform. Press platform away, return controlled.',
        safetyNotes: 'Do not lock knees at top. Keep lower back flat against pad.',
        isSystem: true,
    },
    {
        name: 'Romanian Deadlift',
        category: 'Legs',
        primaryMuscle: 'Hamstrings',
        secondaryMuscles: ['Glutes', 'Erector Spinae'],
        bodyPartFocus: 'Legs',
        equipment: 'barbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
        sourceUrl: 'https://exrx.net/WeightExercises/Hamstrings/BBRomanianDeadlift',
        instructions: 'Stand with bar, hinge at hips with slight knee bend. Lower bar along legs, return.',
        safetyNotes: 'Maintain neutral spine throughout. Feel stretch in hamstrings.',
        isSystem: true,
    },
    {
        name: 'Leg Extension',
        category: 'Legs',
        primaryMuscle: 'Quadriceps',
        secondaryMuscles: [],
        bodyPartFocus: 'Legs',
        equipment: 'machine',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=YyvSfVjQeL0',
        sourceUrl: 'https://exrx.net/WeightExercises/Quadriceps/LVLegExtension',
        instructions: 'Sit in machine, hook ankles under pad. Extend legs fully, lower controlled.',
        safetyNotes: 'Avoid locking knees forcefully. Those with knee issues should use light weight.',
        isSystem: true,
    },
    {
        name: 'Leg Curl',
        category: 'Legs',
        primaryMuscle: 'Hamstrings',
        secondaryMuscles: ['Gastrocnemius'],
        bodyPartFocus: 'Legs',
        equipment: 'machine',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=1Tq3QdYUuHs',
        sourceUrl: 'https://exrx.net/WeightExercises/Hamstrings/LVLegCurl',
        instructions: 'Lie face down on machine. Curl heels toward glutes, lower slowly.',
        safetyNotes: 'Keep hips on pad. Do not hyperextend lower back.',
        isSystem: true,
    },
    {
        name: 'Calf Raise',
        category: 'Legs',
        primaryMuscle: 'Gastrocnemius',
        secondaryMuscles: ['Soleus'],
        bodyPartFocus: 'Legs',
        equipment: 'machine',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=-M4-G8p1fCI',
        sourceUrl: 'https://exrx.net/WeightExercises/Gastrocnemius/LVCalfRaise',
        instructions: 'Stand on edge of platform, heels hanging. Rise onto toes fully, lower below platform level.',
        safetyNotes: 'Full range of motion is key. Avoid bouncing at bottom.',
        isSystem: true,
    },
    {
        name: 'Dumbbell Lunge',
        category: 'Legs',
        primaryMuscle: 'Quadriceps',
        secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
        bodyPartFocus: 'Legs',
        equipment: 'dumbbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=D7KaRcUTQeE',
        sourceUrl: 'https://exrx.net/WeightExercises/Quadriceps/DBLunge',
        instructions: 'Hold dumbbells at sides, step forward into lunge. Lower back knee toward floor, push back.',
        safetyNotes: 'Keep front knee behind toes. Maintain upright torso.',
        isSystem: true,
    },

    // ─── GLUTES ──────────────────────────────────────────────────────────────
    {
        name: 'Hip Thrust',
        category: 'Glutes',
        primaryMuscle: 'Gluteus Maximus',
        secondaryMuscles: ['Hamstrings', 'Core'],
        bodyPartFocus: 'Glutes',
        equipment: 'barbell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=SEdqd1n0cvg',
        sourceUrl: 'https://exrx.net/WeightExercises/GluteMaximus/BBHipThrust',
        instructions: 'Back on bench, bar across hips. Drive hips up until body is straight, squeeze glutes.',
        safetyNotes: 'Pad the barbell. Keep chin tucked.',
        isSystem: true,
    },
    {
        name: 'Glute Bridge',
        category: 'Glutes',
        primaryMuscle: 'Gluteus Maximus',
        secondaryMuscles: ['Hamstrings', 'Core'],
        bodyPartFocus: 'Glutes',
        equipment: 'bodyweight',
        trackingType: 'reps_only',
        demoVideoUrl: 'https://www.youtube.com/watch?v=OUgsJ8-Vi0E',
        sourceUrl: 'https://exrx.net/WeightExercises/GluteMaximus/BWGluteBridge',
        instructions: 'Lie on back, knees bent. Drive hips up squeezing glutes, hold briefly.',
        safetyNotes: 'Keep core engaged. Do not hyperextend lower back.',
        isSystem: true,
    },

    // ─── CORE ────────────────────────────────────────────────────────────────
    {
        name: 'Plank',
        category: 'Core',
        primaryMuscle: 'Transverse Abdominis',
        secondaryMuscles: ['Rectus Abdominis', 'Obliques', 'Erector Spinae'],
        bodyPartFocus: 'Core',
        equipment: 'bodyweight',
        trackingType: 'time',
        demoVideoUrl: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
        sourceUrl: 'https://exrx.net/WeightExercises/RectusAbdominis/BWFrontPlank',
        instructions: 'Forearms on floor, body in straight line. Hold position, breathing steadily.',
        safetyNotes: 'Do not let hips sag or pike. Keep neck neutral.',
        isSystem: true,
    },
    {
        name: 'Side Plank',
        category: 'Core',
        primaryMuscle: 'Obliques',
        secondaryMuscles: ['Transverse Abdominis', 'Gluteus Medius'],
        bodyPartFocus: 'Core',
        equipment: 'bodyweight',
        trackingType: 'time',
        demoVideoUrl: 'https://www.youtube.com/watch?v=K2VljzCC16g',
        sourceUrl: 'https://exrx.net/WeightExercises/Obliques/BWSidePlank',
        instructions: 'Lie on side, prop on forearm. Lift hips to form straight line, hold.',
        safetyNotes: 'Stack feet or stagger for stability. Keep neck in line with spine.',
        isSystem: true,
    },
    {
        name: 'Crunch',
        category: 'Core',
        primaryMuscle: 'Rectus Abdominis',
        secondaryMuscles: ['Obliques'],
        bodyPartFocus: 'Core',
        equipment: 'bodyweight',
        trackingType: 'reps_only',
        demoVideoUrl: 'https://www.youtube.com/watch?v=Xyd_fa5zoEU',
        sourceUrl: 'https://exrx.net/WeightExercises/RectusAbdominis/BWCrunch',
        instructions: 'Lie on back, knees bent. Curl shoulders off floor contracting abs, lower slowly.',
        safetyNotes: 'Do not pull on neck. Focus on contracting abs, not moving elbows.',
        isSystem: true,
    },
    {
        name: 'Hanging Knee Raise',
        category: 'Core',
        primaryMuscle: 'Rectus Abdominis (Lower)',
        secondaryMuscles: ['Hip Flexors', 'Obliques'],
        bodyPartFocus: 'Core',
        equipment: 'bodyweight',
        trackingType: 'reps_only',
        demoVideoUrl: 'https://www.youtube.com/watch?v=Pr1ieGZ5atk',
        sourceUrl: 'https://exrx.net/WeightExercises/HipFlexors/BWHangingKneeRaise',
        instructions: 'Hang from pull-up bar. Raise knees to chest, lower controlled.',
        safetyNotes: 'Avoid swinging. Engage core before lifting.',
        isSystem: true,
    },
    {
        name: 'Russian Twist',
        category: 'Core',
        primaryMuscle: 'Obliques',
        secondaryMuscles: ['Rectus Abdominis'],
        bodyPartFocus: 'Core',
        equipment: 'bodyweight',
        trackingType: 'reps_only',
        demoVideoUrl: 'https://www.youtube.com/watch?v=wkD8rjkodUI',
        sourceUrl: 'https://exrx.net/WeightExercises/Obliques/BWRussianTwist',
        instructions: 'Sit with knees bent, lean back slightly. Rotate torso side to side.',
        safetyNotes: 'Keep back straight. Add weight to increase difficulty.',
        isSystem: true,
    },

    // ─── CARDIO ──────────────────────────────────────────────────────────────
    {
        name: 'Treadmill Run',
        category: 'Cardio',
        primaryMuscle: 'Full Body',
        secondaryMuscles: ['Quadriceps', 'Hamstrings', 'Calves', 'Core'],
        bodyPartFocus: 'Full Body',
        equipment: 'machine',
        trackingType: 'time',
        demoVideoUrl: 'https://www.youtube.com/watch?v=p9MTvzMEAGE',
        sourceUrl: 'https://exrx.net/Aerobic/TreadmillRunning',
        instructions: 'Set desired speed and incline. Maintain upright posture, natural arm swing.',
        safetyNotes: 'Use safety clip. Warm up at low speed. Cool down gradually.',
        isSystem: true,
    },
    {
        name: 'Stationary Cycling',
        category: 'Cardio',
        primaryMuscle: 'Quadriceps',
        secondaryMuscles: ['Hamstrings', 'Calves', 'Glutes'],
        bodyPartFocus: 'Full Body',
        equipment: 'machine',
        trackingType: 'time',
        demoVideoUrl: 'https://www.youtube.com/watch?v=0yXRDCMfMFU',
        sourceUrl: 'https://exrx.net/Aerobic/StationaryCycling',
        instructions: 'Adjust seat so knees have slight bend at bottom. Pedal at consistent cadence.',
        safetyNotes: 'Set resistance to avoid straining knees. Keep pedal stroke smooth.',
        isSystem: true,
    },
    {
        name: 'Rowing Machine',
        category: 'Cardio',
        primaryMuscle: 'Full Body',
        secondaryMuscles: ['Back', 'Legs', 'Core', 'Arms'],
        bodyPartFocus: 'Full Body',
        equipment: 'machine',
        trackingType: 'time',
        demoVideoUrl: 'https://www.youtube.com/watch?v=H0r_AxNhsSk',
        sourceUrl: 'https://exrx.net/Aerobic/Rowing',
        instructions: 'Drive with legs first, lean back, then pull handle to lower chest. Reverse order.',
        safetyNotes: 'Learn technique before increasing resistance. Avoid rounding lower back.',
        isSystem: true,
    },
    {
        name: 'Jump Rope',
        category: 'Cardio',
        primaryMuscle: 'Calves',
        secondaryMuscles: ['Shoulders', 'Core', 'Quadriceps'],
        bodyPartFocus: 'Full Body',
        equipment: 'other',
        trackingType: 'time',
        demoVideoUrl: 'https://www.youtube.com/watch?v=FJmRQ5iTXKE',
        sourceUrl: 'https://exrx.net/Aerobic/JumpRope',
        instructions: 'Keep jumps small, land on balls of feet. Rotate rope with wrists.',
        safetyNotes: 'Jump on a soft surface. Start slow to develop rhythm.',
        isSystem: true,
    },

    // ─── MOBILITY ────────────────────────────────────────────────────────────
    {
        name: 'Hip Flexor Stretch',
        category: 'Mobility',
        primaryMuscle: 'Hip Flexors',
        secondaryMuscles: ['Quadriceps'],
        bodyPartFocus: 'Hips',
        equipment: 'bodyweight',
        trackingType: 'time',
        demoVideoUrl: 'https://www.youtube.com/watch?v=YqF8GvGPIqA',
        sourceUrl: 'https://exrx.net/Stretches/HipFlexors/KneelingHipFlexorStretch',
        instructions: 'Kneeling lunge position. Shift forward until stretch in front of hip, hold.',
        safetyNotes: 'Do not arch lower back. Keep front knee above ankle.',
        isSystem: true,
    },
    {
        name: 'Cat-Cow Stretch',
        category: 'Mobility',
        primaryMuscle: 'Erector Spinae',
        secondaryMuscles: ['Abdominals', 'Hip Flexors'],
        bodyPartFocus: 'Spine',
        equipment: 'bodyweight',
        trackingType: 'reps_only',
        demoVideoUrl: 'https://www.youtube.com/watch?v=kqnua4rHVVA',
        sourceUrl: 'https://exrx.net/Stretches/BackGeneral/CatCow',
        instructions: 'On all fours, alternate between arching (cat) and dropping (cow) your spine.',
        safetyNotes: 'Move slowly and with breath. Great morning warm-up.',
        isSystem: true,
    },
    {
        name: 'World\'s Greatest Stretch',
        category: 'Mobility',
        primaryMuscle: 'Hip Flexors',
        secondaryMuscles: ['Thoracic Spine', 'Hamstrings', 'Glutes'],
        bodyPartFocus: 'Full Body',
        equipment: 'bodyweight',
        trackingType: 'reps_only',
        demoVideoUrl: 'https://www.youtube.com/watch?v=iXSbCcAO0so',
        sourceUrl: 'https://www.verywellfit.com/worlds-greatest-stretch-4588474',
        instructions: 'Lunge forward, place same-side hand inside foot. Rotate and reach overhead.',
        safetyNotes: 'Move through full range gently. Breathe throughout.',
        isSystem: true,
    },

    // ─── FULL BODY ───────────────────────────────────────────────────────────
    {
        name: 'Burpee',
        category: 'Full Body',
        primaryMuscle: 'Full Body',
        secondaryMuscles: ['Chest', 'Shoulders', 'Core', 'Legs'],
        bodyPartFocus: 'Full Body',
        equipment: 'bodyweight',
        trackingType: 'reps_only',
        demoVideoUrl: 'https://www.youtube.com/watch?v=auBLPXO8Fww',
        sourceUrl: 'https://exrx.net/Aerobic/Burpee',
        instructions: 'Stand, drop to squat, kick feet back to plank, push-up, return to squat, jump up.',
        safetyNotes: 'Modify by stepping instead of jumping if needed. Land softly.',
        isSystem: true,
    },
    {
        name: 'Kettlebell Swing',
        category: 'Full Body',
        primaryMuscle: 'Glutes',
        secondaryMuscles: ['Hamstrings', 'Core', 'Shoulders', 'Back'],
        bodyPartFocus: 'Full Body',
        equipment: 'kettlebell',
        trackingType: 'reps_weight',
        demoVideoUrl: 'https://www.youtube.com/watch?v=YSxHifyI6s8',
        sourceUrl: 'https://exrx.net/WeightExercises/GluteMaximus/KBSwing',
        instructions: 'Hip hinge to swing kettlebell back, drive hips forward to swing to shoulder height.',
        safetyNotes: 'This is a hip hinge, not a squat. Keep back flat. Use glute drive.',
        isSystem: true,
    },
];

async function main() {
    console.log('Seeding exercise library...');

    // Clear existing system exercises
    await prisma.exercise.deleteMany({ where: { isSystem: true } });

    for (const exercise of exercises) {
        await prisma.exercise.create({ data: exercise });
    }

    console.log(`Seeded ${exercises.length} exercises.`);
}

main()
    .catch(e => { console.error(e); process.exit(1); })
    .finally(async () => { await prisma.$disconnect(); });
